//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GsisServicesLib.GreekLegalEntityInfoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RgWsPublicInputRtBase", Namespace="http://gr/gsis/rgwspublic/RgWsPublic.wsdl")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GsisServicesLib.GreekLegalEntityInfoService.RgWsPublicInputRtUser))]
    public partial class RgWsPublicInputRtBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RgWsPublicInputRtUser", Namespace="http://gr/gsis/rgwspublic/RgWsPublic.wsdl")]
    [System.SerializableAttribute()]
    public partial class RgWsPublicInputRtUser : GsisServicesLib.GreekLegalEntityInfoService.RgWsPublicInputRtBase {
        
        private string afmCalledByField;
        
        private string afmCalledForField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string afmCalledBy {
            get {
                return this.afmCalledByField;
            }
            set {
                if ((object.ReferenceEquals(this.afmCalledByField, value) != true)) {
                    this.afmCalledByField = value;
                    this.RaisePropertyChanged("afmCalledBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string afmCalledFor {
            get {
                return this.afmCalledForField;
            }
            set {
                if ((object.ReferenceEquals(this.afmCalledForField, value) != true)) {
                    this.afmCalledForField = value;
                    this.RaisePropertyChanged("afmCalledFor");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RgWsPublicBasicRtBase", Namespace="http://gr/gsis/rgwspublic/RgWsPublic.wsdl")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GsisServicesLib.GreekLegalEntityInfoService.RgWsPublicBasicRtUser))]
    public partial class RgWsPublicBasicRtBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RgWsPublicBasicRtUser", Namespace="http://gr/gsis/rgwspublic/RgWsPublic.wsdl")]
    [System.SerializableAttribute()]
    public partial class RgWsPublicBasicRtUser : GsisServicesLib.GreekLegalEntityInfoService.RgWsPublicBasicRtBase {
        
        private string afmField;
        
        private System.Nullable<System.DateTime> stopDateField;
        
        private string postalAddressNoField;
        
        private string doyDescrField;
        
        private string doyField;
        
        private string onomasiaField;
        
        private string legalStatusDescrField;
        
        private System.Nullable<System.DateTime> registDateField;
        
        private string deactivationFlagField;
        
        private string deactivationFlagDescrField;
        
        private string postalAddressField;
        
        private string firmFlagDescrField;
        
        private string commerTitleField;
        
        private string postalAreaDescriptionField;
        
        private string INiFlagDescrField;
        
        private string postalZipCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string afm {
            get {
                return this.afmField;
            }
            set {
                if ((object.ReferenceEquals(this.afmField, value) != true)) {
                    this.afmField = value;
                    this.RaisePropertyChanged("afm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> stopDate {
            get {
                return this.stopDateField;
            }
            set {
                if ((this.stopDateField.Equals(value) != true)) {
                    this.stopDateField = value;
                    this.RaisePropertyChanged("stopDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string postalAddressNo {
            get {
                return this.postalAddressNoField;
            }
            set {
                if ((object.ReferenceEquals(this.postalAddressNoField, value) != true)) {
                    this.postalAddressNoField = value;
                    this.RaisePropertyChanged("postalAddressNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string doyDescr {
            get {
                return this.doyDescrField;
            }
            set {
                if ((object.ReferenceEquals(this.doyDescrField, value) != true)) {
                    this.doyDescrField = value;
                    this.RaisePropertyChanged("doyDescr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string doy {
            get {
                return this.doyField;
            }
            set {
                if ((object.ReferenceEquals(this.doyField, value) != true)) {
                    this.doyField = value;
                    this.RaisePropertyChanged("doy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string onomasia {
            get {
                return this.onomasiaField;
            }
            set {
                if ((object.ReferenceEquals(this.onomasiaField, value) != true)) {
                    this.onomasiaField = value;
                    this.RaisePropertyChanged("onomasia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string legalStatusDescr {
            get {
                return this.legalStatusDescrField;
            }
            set {
                if ((object.ReferenceEquals(this.legalStatusDescrField, value) != true)) {
                    this.legalStatusDescrField = value;
                    this.RaisePropertyChanged("legalStatusDescr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<System.DateTime> registDate {
            get {
                return this.registDateField;
            }
            set {
                if ((this.registDateField.Equals(value) != true)) {
                    this.registDateField = value;
                    this.RaisePropertyChanged("registDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public string deactivationFlag {
            get {
                return this.deactivationFlagField;
            }
            set {
                if ((object.ReferenceEquals(this.deactivationFlagField, value) != true)) {
                    this.deactivationFlagField = value;
                    this.RaisePropertyChanged("deactivationFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public string deactivationFlagDescr {
            get {
                return this.deactivationFlagDescrField;
            }
            set {
                if ((object.ReferenceEquals(this.deactivationFlagDescrField, value) != true)) {
                    this.deactivationFlagDescrField = value;
                    this.RaisePropertyChanged("deactivationFlagDescr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public string postalAddress {
            get {
                return this.postalAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.postalAddressField, value) != true)) {
                    this.postalAddressField = value;
                    this.RaisePropertyChanged("postalAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public string firmFlagDescr {
            get {
                return this.firmFlagDescrField;
            }
            set {
                if ((object.ReferenceEquals(this.firmFlagDescrField, value) != true)) {
                    this.firmFlagDescrField = value;
                    this.RaisePropertyChanged("firmFlagDescr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public string commerTitle {
            get {
                return this.commerTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.commerTitleField, value) != true)) {
                    this.commerTitleField = value;
                    this.RaisePropertyChanged("commerTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public string postalAreaDescription {
            get {
                return this.postalAreaDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.postalAreaDescriptionField, value) != true)) {
                    this.postalAreaDescriptionField = value;
                    this.RaisePropertyChanged("postalAreaDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public string INiFlagDescr {
            get {
                return this.INiFlagDescrField;
            }
            set {
                if ((object.ReferenceEquals(this.INiFlagDescrField, value) != true)) {
                    this.INiFlagDescrField = value;
                    this.RaisePropertyChanged("INiFlagDescr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public string postalZipCode {
            get {
                return this.postalZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.postalZipCodeField, value) != true)) {
                    this.postalZipCodeField = value;
                    this.RaisePropertyChanged("postalZipCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="RgWsPublicFirmActRtUserArray", Namespace="http://gr/gsis/rgwspublic/RgWsPublic.wsdl", ItemName="RgWsPublicFirmActRtUser")]
    [System.SerializableAttribute()]
    public class RgWsPublicFirmActRtUserArray : System.Collections.Generic.List<GsisServicesLib.GreekLegalEntityInfoService.RgWsPublicFirmActRtUser> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RgWsPublicFirmActRtUser", Namespace="http://gr/gsis/rgwspublic/RgWsPublic.wsdl")]
    [System.SerializableAttribute()]
    public partial class RgWsPublicFirmActRtUser : GsisServicesLib.GreekLegalEntityInfoService.RgWsPublicFirmActRtBase {
        
        private string firmActDescrField;
        
        private string firmActKindField;
        
        private string firmActKindDescrField;
        
        private System.Nullable<decimal> firmActCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string firmActDescr {
            get {
                return this.firmActDescrField;
            }
            set {
                if ((object.ReferenceEquals(this.firmActDescrField, value) != true)) {
                    this.firmActDescrField = value;
                    this.RaisePropertyChanged("firmActDescr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string firmActKind {
            get {
                return this.firmActKindField;
            }
            set {
                if ((object.ReferenceEquals(this.firmActKindField, value) != true)) {
                    this.firmActKindField = value;
                    this.RaisePropertyChanged("firmActKind");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string firmActKindDescr {
            get {
                return this.firmActKindDescrField;
            }
            set {
                if ((object.ReferenceEquals(this.firmActKindDescrField, value) != true)) {
                    this.firmActKindDescrField = value;
                    this.RaisePropertyChanged("firmActKindDescr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<decimal> firmActCode {
            get {
                return this.firmActCodeField;
            }
            set {
                if ((this.firmActCodeField.Equals(value) != true)) {
                    this.firmActCodeField = value;
                    this.RaisePropertyChanged("firmActCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RgWsPublicFirmActRtBase", Namespace="http://gr/gsis/rgwspublic/RgWsPublic.wsdl")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GsisServicesLib.GreekLegalEntityInfoService.RgWsPublicFirmActRtUser))]
    public partial class RgWsPublicFirmActRtBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenWsErrorRtBase", Namespace="http://gr/gsis/rgwspublic/RgWsPublic.wsdl")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GsisServicesLib.GreekLegalEntityInfoService.GenWsErrorRtUser))]
    public partial class GenWsErrorRtBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenWsErrorRtUser", Namespace="http://gr/gsis/rgwspublic/RgWsPublic.wsdl")]
    [System.SerializableAttribute()]
    public partial class GenWsErrorRtUser : GsisServicesLib.GreekLegalEntityInfoService.GenWsErrorRtBase {
        
        private string errorDescrField;
        
        private string errorCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string errorDescr {
            get {
                return this.errorDescrField;
            }
            set {
                if ((object.ReferenceEquals(this.errorDescrField, value) != true)) {
                    this.errorDescrField = value;
                    this.RaisePropertyChanged("errorDescr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.errorCodeField, value) != true)) {
                    this.errorCodeField = value;
                    this.RaisePropertyChanged("errorCode");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gr/gsis/rgwspublic/RgWsPublic.wsdl", ConfigurationName="GreekLegalEntityInfoService.RgWsPublic")]
    public interface RgWsPublic {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gr/gsis/rgwspublic/RgWsPublic.wsdl/rgWsPublicAfmMethod", ReplyAction="*")]
        GsisServicesLib.GreekLegalEntityInfoService.rgWsPublicAfmMethodResponse rgWsPublicAfmMethod(GsisServicesLib.GreekLegalEntityInfoService.rgWsPublicAfmMethodRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://gr/gsis/rgwspublic/RgWsPublic.wsdl/rgWsPublicAfmMethod", ReplyAction="*")]
        System.Threading.Tasks.Task<GsisServicesLib.GreekLegalEntityInfoService.rgWsPublicAfmMethodResponse> rgWsPublicAfmMethodAsync(GsisServicesLib.GreekLegalEntityInfoService.rgWsPublicAfmMethodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gr/gsis/rgwspublic/RgWsPublic.wsdl/rgWsPublicVersionInfo", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string rgWsPublicVersionInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gr/gsis/rgwspublic/RgWsPublic.wsdl/rgWsPublicVersionInfo", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<string> rgWsPublicVersionInfoAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rgWsPublicAfmMethod", WrapperNamespace="http://gr/gsis/rgwspublic/RgWsPublic.wsdl", IsWrapped=true)]
    public partial class rgWsPublicAfmMethodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public GsisServicesLib.GreekLegalEntityInfoService.RgWsPublicInputRtUser RgWsPublicInputRt_in;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public GsisServicesLib.GreekLegalEntityInfoService.RgWsPublicBasicRtUser RgWsPublicBasicRt_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public GsisServicesLib.GreekLegalEntityInfoService.RgWsPublicFirmActRtUserArray arrayOfRgWsPublicFirmActRt_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public decimal pCallSeqId_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public GsisServicesLib.GreekLegalEntityInfoService.GenWsErrorRtUser pErrorRec_out;
        
        public rgWsPublicAfmMethodRequest() {
        }
        
        public rgWsPublicAfmMethodRequest(GsisServicesLib.GreekLegalEntityInfoService.RgWsPublicInputRtUser RgWsPublicInputRt_in, GsisServicesLib.GreekLegalEntityInfoService.RgWsPublicBasicRtUser RgWsPublicBasicRt_out, GsisServicesLib.GreekLegalEntityInfoService.RgWsPublicFirmActRtUserArray arrayOfRgWsPublicFirmActRt_out, decimal pCallSeqId_out, GsisServicesLib.GreekLegalEntityInfoService.GenWsErrorRtUser pErrorRec_out) {
            this.RgWsPublicInputRt_in = RgWsPublicInputRt_in;
            this.RgWsPublicBasicRt_out = RgWsPublicBasicRt_out;
            this.arrayOfRgWsPublicFirmActRt_out = arrayOfRgWsPublicFirmActRt_out;
            this.pCallSeqId_out = pCallSeqId_out;
            this.pErrorRec_out = pErrorRec_out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rgWsPublicAfmMethodResponse", WrapperNamespace="http://gr/gsis/rgwspublic/RgWsPublic.wsdl", IsWrapped=true)]
    public partial class rgWsPublicAfmMethodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public GsisServicesLib.GreekLegalEntityInfoService.RgWsPublicBasicRtUser RgWsPublicBasicRt_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public GsisServicesLib.GreekLegalEntityInfoService.RgWsPublicFirmActRtUserArray arrayOfRgWsPublicFirmActRt_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public decimal pCallSeqId_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public GsisServicesLib.GreekLegalEntityInfoService.GenWsErrorRtUser pErrorRec_out;
        
        public rgWsPublicAfmMethodResponse() {
        }
        
        public rgWsPublicAfmMethodResponse(GsisServicesLib.GreekLegalEntityInfoService.RgWsPublicBasicRtUser RgWsPublicBasicRt_out, GsisServicesLib.GreekLegalEntityInfoService.RgWsPublicFirmActRtUserArray arrayOfRgWsPublicFirmActRt_out, decimal pCallSeqId_out, GsisServicesLib.GreekLegalEntityInfoService.GenWsErrorRtUser pErrorRec_out) {
            this.RgWsPublicBasicRt_out = RgWsPublicBasicRt_out;
            this.arrayOfRgWsPublicFirmActRt_out = arrayOfRgWsPublicFirmActRt_out;
            this.pCallSeqId_out = pCallSeqId_out;
            this.pErrorRec_out = pErrorRec_out;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RgWsPublicChannel : GsisServicesLib.GreekLegalEntityInfoService.RgWsPublic, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RgWsPublicClient : System.ServiceModel.ClientBase<GsisServicesLib.GreekLegalEntityInfoService.RgWsPublic>, GsisServicesLib.GreekLegalEntityInfoService.RgWsPublic {
        
        public RgWsPublicClient() {
        }
        
        public RgWsPublicClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RgWsPublicClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RgWsPublicClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RgWsPublicClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GsisServicesLib.GreekLegalEntityInfoService.rgWsPublicAfmMethodResponse GsisServicesLib.GreekLegalEntityInfoService.RgWsPublic.rgWsPublicAfmMethod(GsisServicesLib.GreekLegalEntityInfoService.rgWsPublicAfmMethodRequest request) {
            return base.Channel.rgWsPublicAfmMethod(request);
        }
        
        public void rgWsPublicAfmMethod(GsisServicesLib.GreekLegalEntityInfoService.RgWsPublicInputRtUser RgWsPublicInputRt_in, ref GsisServicesLib.GreekLegalEntityInfoService.RgWsPublicBasicRtUser RgWsPublicBasicRt_out, ref GsisServicesLib.GreekLegalEntityInfoService.RgWsPublicFirmActRtUserArray arrayOfRgWsPublicFirmActRt_out, ref decimal pCallSeqId_out, ref GsisServicesLib.GreekLegalEntityInfoService.GenWsErrorRtUser pErrorRec_out) {
            GsisServicesLib.GreekLegalEntityInfoService.rgWsPublicAfmMethodRequest inValue = new GsisServicesLib.GreekLegalEntityInfoService.rgWsPublicAfmMethodRequest();
            inValue.RgWsPublicInputRt_in = RgWsPublicInputRt_in;
            inValue.RgWsPublicBasicRt_out = RgWsPublicBasicRt_out;
            inValue.arrayOfRgWsPublicFirmActRt_out = arrayOfRgWsPublicFirmActRt_out;
            inValue.pCallSeqId_out = pCallSeqId_out;
            inValue.pErrorRec_out = pErrorRec_out;
            GsisServicesLib.GreekLegalEntityInfoService.rgWsPublicAfmMethodResponse retVal = ((GsisServicesLib.GreekLegalEntityInfoService.RgWsPublic)(this)).rgWsPublicAfmMethod(inValue);
            RgWsPublicBasicRt_out = retVal.RgWsPublicBasicRt_out;
            arrayOfRgWsPublicFirmActRt_out = retVal.arrayOfRgWsPublicFirmActRt_out;
            pCallSeqId_out = retVal.pCallSeqId_out;
            pErrorRec_out = retVal.pErrorRec_out;
        }
        
        public System.Threading.Tasks.Task<GsisServicesLib.GreekLegalEntityInfoService.rgWsPublicAfmMethodResponse> rgWsPublicAfmMethodAsync(GsisServicesLib.GreekLegalEntityInfoService.rgWsPublicAfmMethodRequest request) {
            return base.Channel.rgWsPublicAfmMethodAsync(request);
        }
        
        public string rgWsPublicVersionInfo() {
            return base.Channel.rgWsPublicVersionInfo();
        }
        
        public System.Threading.Tasks.Task<string> rgWsPublicVersionInfoAsync() {
            return base.Channel.rgWsPublicVersionInfoAsync();
        }
    }
}
